### ISSUE TITLE
How complete and up-to-date is this binding?

### ISSUE THREAD

**Issue by NinthDesertDude** [codefoco/ChipmunkBinding#27]
It's 2019 and C#'s only hold on games is basically MonoGame. There are 2 main ports of Box2D for C#, and one of those died on CodePlex. The other is little known. The Cocos2d port for XNA seems the best choice there is for development in MonoGame in 2019 since it includes Box2D itself, but I don't want Cocos2D. Just trying to explain why I'm here (thanks, Nuget package search).

Looks like you're not just recent, but you started in April. I'd like to get your opinion on how complete these bindings are to gauge if they're ready for actual use and if they've been tested thoroughly. Thanks!

**Comment by viniciusjarina** [comment]
Hi @JoshuaLamusga I would say 99.9% complete

The only API I didn't bind was the `ConvexHull`, but all other Chipmunk C APIs should be surfaced and documented on C#.

Let me know if you have any issue.

**Comment by NinthDesertDude** [comment]
Will do.
