### ISSUE TITLE
CollisionType is an int, but should be an enum

### ISSUE THREAD

**Issue by NinthDesertDude** [codefoco/ChipmunkBinding#28]
Shape has a property called CollisionType which is currently just an integer. It should be updated to an enum so I know what the values passed in represent. (If it's supposed to be an integer, the description needs to be updated to explain it better.)

**Version:** 1.0.5 (Nuget version)

**Comment by viniciusjarina** [comment]
Is a arbitrary value. You can wrap with your own enum on your application code. But thank you for reporting.

**Comment by NinthDesertDude** [comment]
@viniciusjarina It would be helpful if the description mentioned what the purpose of CollisionType was, then, e.g. "Only shapes with the same collision type can collide" (that's my assumption).

**Comment by viniciusjarina** [comment]
Oh OK. Most of documentation is from Chipmunk header files. I would be happy to fix the documentation. If you send the PR I can merge it
Thank you.
