### ISSUE TITLE
What does radius do in the Box() constructor?

### ISSUE THREAD

**Issue by NinthDesertDude** [codefoco/ChipmunkBinding#29]
You can pass width and height, so what does radius do? I would think it makes a square, but not when you can define all attributes at once.

**Comment by viniciusjarina** [comment]
Is the radius of the edge of the box.
I think is good idea to be familiar with Chipmunk API https://chipmunk-physics.net/release/ChipmunkLatest-API-Reference/interface_chipmunk_poly_shape.html#a7956bfc289a6753eb70ae3d7fa9451c8
